**Vector**
  - Ai models does not understand text,he understand numbers only
  - A numerical representation of text is called vectors

**Embedding**
   - Any numbers is called vectors but the meaning of numbers is embedding
   - it is a process of converting text in numbers with some meaning

- Why vectors?
   - Because vector gives direction if the vector has same direction means text has similiar meaining,if different directions both text has different          meaning

**Cosine similarity**
   - It measure how similar two vectors are by checking the angle between them
   - basically it checks how similar the meaining of two text are
   - *1* is exactly same meaning
   - *0* is no relation
   - *-1* is opposite meaning

In [2]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
#two square brackets bcz machine larning functions expect vectors as in 2d array
v1=np.array([[1,2]])
v2=np.array([[2,4]])
v3=np.array([[-1,-2]])

In [4]:
#same direction and very similar
cosine_similarity(v1,v2)

array([[1.]])

In [7]:
#opposite direction
cosine_similarity(v1,v3)

array([[-1.]])

In [26]:
#pip install sentence-transformers


In [1]:
from sentence_transformers import SentenceTransformer
sentence=["cat is sleep on sofa",
          "virat kohli has 37 years of age",
          "the capital of India is Delhi",
          "Trump is the current President of USA"]

In [3]:
#here i am taking ai brain name: all-MiniLM-L6-V2, its free protocol model
#MiniLM → tiny focused brain, only understands meaning and outputs vectors, doesn’t generate text
model=SentenceTransformer("all-MiniLM-L6-V2")
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [4]:
#encode is here to give sentences to model,now model convert text-numbers-embedding(meaning to numebers) then encode returns vector
embeddings=model.encode(sentence)
len(embeddings)

4

In [11]:
len(embeddings[0])

384

In [20]:
v1=embeddings[0]
v2=embeddings[1]
v3=embeddings[2]
v4=embeddings[3]

In [6]:
question="what is age of virat kohli"

In [7]:
qv=model.encode(question)
len(qv)

384

In [16]:
v1.shape,qv.shape

((384,), (384,))

In [22]:
cosine_similarity([v1],[qv])

array([[-0.02913489]], dtype=float32)

In [23]:
cosine_similarity([v2],[qv])

array([[0.9212215]], dtype=float32)

In [24]:
cosine_similarity([v3],[qv])

array([[0.12523368]], dtype=float32)

In [25]:
cosine_similarity([v3],[qv])

array([[0.12523368]], dtype=float32)